openapi: 3.0.0
info:
  title: Code Generation API
  version: 1.0.0
servers:
- url: http://33.227.17.219/v1/apigen
paths:
  /generate/code:
    post:
      operationId: generate_code_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_generate_code_post_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              example:
                message: Code generated successfully. Please refresh with Git.
              schema:
                $ref: '#/components/schemas/_generate_code_post_200_response'
          description: Code generated successfully
        "400":
          content:
            application/json:
              example:
                message: Invalid request. Please provide a valid programming language
                  and OpenAPI specification URL.
              schema:
                $ref: '#/components/schemas/_generate_code_post_400_response'
          description: Bad request
      summary: Generate code from OpenAPI specification
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    _generate_code_post_request:
      properties:
        language:
          description: The programming language to generate code for
          title: language
          type: string
        openAPIUrl:
          description: The URL of the OpenAPI specification to generate code from
          title: openAPIUrl
          type: string
      required:
      - language
      - openAPIUrl
      title: _generate_code_post_request
      type: object
    _generate_code_post_200_response:
      example:
        message: message
      properties:
        message:
          description: A message indicating that code generation was successful
          title: message
          type: string
      title: _generate_code_post_200_response
      type: object
    _generate_code_post_400_response:
      properties:
        message:
          description: A message indicating that the request was invalid
          title: message
          type: string
      title: _generate_code_post_400_response
      type: object
