=begin
#Code Generation API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::GenerateCodePostRequestDto
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::GenerateCodePostRequest do
  let(:instance) { OpenapiClient::GenerateCodePostRequest.new }

  describe 'test an instance of GenerateCodePostRequest' do
    it 'should create an instance of GenerateCodePostRequest' do
      expect(instance).to be_instance_of(OpenapiClient::GenerateCodePostRequest)
    end
  end
  describe 'test attribute "language"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "open_api_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
