/*
 * Swagger Student Management System - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICourseApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Add a new course
        /// </summary>
        /// <remarks>
        /// Add a new course
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Create a new course</param>
        /// <returns>Course</returns>
        Course AddCourse (Course course);

        /// <summary>
        /// Add a new course
        /// </summary>
        /// <remarks>
        /// Add a new course
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Create a new course</param>
        /// <returns>ApiResponse of Course</returns>
        ApiResponse<Course> AddCourseWithHttpInfo (Course course);
        /// <summary>
        /// Deletes a course
        /// </summary>
        /// <remarks>
        /// delete a course
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">Course id to delete</param>
        /// <returns>Course</returns>
        Course DeleteCourse (long courseId);

        /// <summary>
        /// Deletes a course
        /// </summary>
        /// <remarks>
        /// delete a course
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">Course id to delete</param>
        /// <returns>ApiResponse of Course</returns>
        ApiResponse<Course> DeleteCourseWithHttpInfo (long courseId);
        /// <summary>
        /// Find course by ID
        /// </summary>
        /// <remarks>
        /// Returns a single course
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">ID of course to return</param>
        /// <returns>Course</returns>
        Course GetCourse (long courseId);

        /// <summary>
        /// Find course by ID
        /// </summary>
        /// <remarks>
        /// Returns a single course
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">ID of course to return</param>
        /// <returns>ApiResponse of Course</returns>
        ApiResponse<Course> GetCourseWithHttpInfo (long courseId);
        /// <summary>
        /// Get list of all courses
        /// </summary>
        /// <remarks>
        /// Returns list of courses
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List<Course></returns>
        List<Course> GetCourseList ();

        /// <summary>
        /// Get list of all courses
        /// </summary>
        /// <remarks>
        /// Returns list of courses
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List<Course></returns>
        ApiResponse<List<Course>> GetCourseListWithHttpInfo ();
        /// <summary>
        /// Update an existing course
        /// </summary>
        /// <remarks>
        /// Update an existing course by Id
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Update an existent course</param>
        /// <returns>Course</returns>
        Course UpdateCourse (Course course);

        /// <summary>
        /// Update an existing course
        /// </summary>
        /// <remarks>
        /// Update an existing course by Id
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Update an existent course</param>
        /// <returns>ApiResponse of Course</returns>
        ApiResponse<Course> UpdateCourseWithHttpInfo (Course course);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Add a new course
        /// </summary>
        /// <remarks>
        /// Add a new course
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Create a new course</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Course</returns>
        System.Threading.Tasks.Task<Course> AddCourseAsync (Course course, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Add a new course
        /// </summary>
        /// <remarks>
        /// Add a new course
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Create a new course</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Course)</returns>
        System.Threading.Tasks.Task<ApiResponse<Course>> AddCourseWithHttpInfoAsync (Course course, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Deletes a course
        /// </summary>
        /// <remarks>
        /// delete a course
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">Course id to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Course</returns>
        System.Threading.Tasks.Task<Course> DeleteCourseAsync (long courseId, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Deletes a course
        /// </summary>
        /// <remarks>
        /// delete a course
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">Course id to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Course)</returns>
        System.Threading.Tasks.Task<ApiResponse<Course>> DeleteCourseWithHttpInfoAsync (long courseId, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Find course by ID
        /// </summary>
        /// <remarks>
        /// Returns a single course
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">ID of course to return</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Course</returns>
        System.Threading.Tasks.Task<Course> GetCourseAsync (long courseId, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Find course by ID
        /// </summary>
        /// <remarks>
        /// Returns a single course
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">ID of course to return</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Course)</returns>
        System.Threading.Tasks.Task<ApiResponse<Course>> GetCourseWithHttpInfoAsync (long courseId, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Get list of all courses
        /// </summary>
        /// <remarks>
        /// Returns list of courses
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of List<Course></returns>
        System.Threading.Tasks.Task<List<Course>> GetCourseListAsync (CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get list of all courses
        /// </summary>
        /// <remarks>
        /// Returns list of courses
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (List&lt;Course&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Course>>> GetCourseListWithHttpInfoAsync (CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Update an existing course
        /// </summary>
        /// <remarks>
        /// Update an existing course by Id
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Update an existent course</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Course</returns>
        System.Threading.Tasks.Task<Course> UpdateCourseAsync (Course course, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Update an existing course
        /// </summary>
        /// <remarks>
        /// Update an existing course by Id
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Update an existent course</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Course)</returns>
        System.Threading.Tasks.Task<ApiResponse<Course>> UpdateCourseWithHttpInfoAsync (Course course, CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CourseApi : ICourseApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CourseApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CourseApi(String basePath)
        {
            this.Configuration = new Org.OpenAPITools.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CourseApi"/> class
        /// </summary>
        /// <returns></returns>
        public CourseApi()
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.Default;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CourseApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CourseApi(Org.OpenAPITools.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Org.OpenAPITools.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Add a new course Add a new course
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Create a new course</param>
        /// <returns>Course</returns>
        public Course AddCourse (Course course)
        {
             ApiResponse<Course> localVarResponse = AddCourseWithHttpInfo(course);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Add a new course Add a new course
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Create a new course</param>
        /// <returns>ApiResponse of Course</returns>
        public ApiResponse<Course> AddCourseWithHttpInfo (Course course)
        {
            // verify the required parameter 'course' is set
            if (course == null)
                throw new ApiException(400, "Missing required parameter 'course' when calling CourseApi->AddCourse");

            var localVarPath = "/course";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (course != null && course.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(course); // http body (model) parameter
            }
            else
            {
                localVarPostBody = course; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddCourse", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Course>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Course) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Course)));
        }

        /// <summary>
        /// Add a new course Add a new course
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Create a new course</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Course</returns>
        public async System.Threading.Tasks.Task<Course> AddCourseAsync (Course course, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<Course> localVarResponse = await AddCourseWithHttpInfoAsync(course, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Add a new course Add a new course
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Create a new course</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Course)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Course>> AddCourseWithHttpInfoAsync (Course course, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'course' is set
            if (course == null)
                throw new ApiException(400, "Missing required parameter 'course' when calling CourseApi->AddCourse");

            var localVarPath = "/course";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (course != null && course.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(course); // http body (model) parameter
            }
            else
            {
                localVarPostBody = course; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddCourse", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Course>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Course) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Course)));
        }

        /// <summary>
        /// Deletes a course delete a course
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">Course id to delete</param>
        /// <returns>Course</returns>
        public Course DeleteCourse (long courseId)
        {
             ApiResponse<Course> localVarResponse = DeleteCourseWithHttpInfo(courseId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Deletes a course delete a course
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">Course id to delete</param>
        /// <returns>ApiResponse of Course</returns>
        public ApiResponse<Course> DeleteCourseWithHttpInfo (long courseId)
        {
            // verify the required parameter 'courseId' is set
            if (courseId == null)
                throw new ApiException(400, "Missing required parameter 'courseId' when calling CourseApi->DeleteCourse");

            var localVarPath = "/course/{courseId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (courseId != null) localVarPathParams.Add("courseId", this.Configuration.ApiClient.ParameterToString(courseId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteCourse", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Course>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Course) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Course)));
        }

        /// <summary>
        /// Deletes a course delete a course
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">Course id to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Course</returns>
        public async System.Threading.Tasks.Task<Course> DeleteCourseAsync (long courseId, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<Course> localVarResponse = await DeleteCourseWithHttpInfoAsync(courseId, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Deletes a course delete a course
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">Course id to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Course)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Course>> DeleteCourseWithHttpInfoAsync (long courseId, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'courseId' is set
            if (courseId == null)
                throw new ApiException(400, "Missing required parameter 'courseId' when calling CourseApi->DeleteCourse");

            var localVarPath = "/course/{courseId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (courseId != null) localVarPathParams.Add("courseId", this.Configuration.ApiClient.ParameterToString(courseId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteCourse", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Course>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Course) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Course)));
        }

        /// <summary>
        /// Find course by ID Returns a single course
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">ID of course to return</param>
        /// <returns>Course</returns>
        public Course GetCourse (long courseId)
        {
             ApiResponse<Course> localVarResponse = GetCourseWithHttpInfo(courseId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Find course by ID Returns a single course
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">ID of course to return</param>
        /// <returns>ApiResponse of Course</returns>
        public ApiResponse<Course> GetCourseWithHttpInfo (long courseId)
        {
            // verify the required parameter 'courseId' is set
            if (courseId == null)
                throw new ApiException(400, "Missing required parameter 'courseId' when calling CourseApi->GetCourse");

            var localVarPath = "/course/{courseId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (courseId != null) localVarPathParams.Add("courseId", this.Configuration.ApiClient.ParameterToString(courseId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCourse", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Course>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Course) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Course)));
        }

        /// <summary>
        /// Find course by ID Returns a single course
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">ID of course to return</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Course</returns>
        public async System.Threading.Tasks.Task<Course> GetCourseAsync (long courseId, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<Course> localVarResponse = await GetCourseWithHttpInfoAsync(courseId, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Find course by ID Returns a single course
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="courseId">ID of course to return</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Course)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Course>> GetCourseWithHttpInfoAsync (long courseId, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'courseId' is set
            if (courseId == null)
                throw new ApiException(400, "Missing required parameter 'courseId' when calling CourseApi->GetCourse");

            var localVarPath = "/course/{courseId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (courseId != null) localVarPathParams.Add("courseId", this.Configuration.ApiClient.ParameterToString(courseId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCourse", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Course>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Course) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Course)));
        }

        /// <summary>
        /// Get list of all courses Returns list of courses
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List<Course></returns>
        public List<Course> GetCourseList ()
        {
             ApiResponse<List<Course>> localVarResponse = GetCourseListWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get list of all courses Returns list of courses
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List<Course></returns>
        public ApiResponse<List<Course>> GetCourseListWithHttpInfo ()
        {

            var localVarPath = "/course";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCourseList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Course>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Course>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Course>)));
        }

        /// <summary>
        /// Get list of all courses Returns list of courses
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of List<Course></returns>
        public async System.Threading.Tasks.Task<List<Course>> GetCourseListAsync (CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<List<Course>> localVarResponse = await GetCourseListWithHttpInfoAsync(cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get list of all courses Returns list of courses
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (List&lt;Course&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Course>>> GetCourseListWithHttpInfoAsync (CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/course";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetCourseList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Course>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Course>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Course>)));
        }

        /// <summary>
        /// Update an existing course Update an existing course by Id
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Update an existent course</param>
        /// <returns>Course</returns>
        public Course UpdateCourse (Course course)
        {
             ApiResponse<Course> localVarResponse = UpdateCourseWithHttpInfo(course);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update an existing course Update an existing course by Id
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Update an existent course</param>
        /// <returns>ApiResponse of Course</returns>
        public ApiResponse<Course> UpdateCourseWithHttpInfo (Course course)
        {
            // verify the required parameter 'course' is set
            if (course == null)
                throw new ApiException(400, "Missing required parameter 'course' when calling CourseApi->UpdateCourse");

            var localVarPath = "/course";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (course != null && course.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(course); // http body (model) parameter
            }
            else
            {
                localVarPostBody = course; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateCourse", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Course>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Course) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Course)));
        }

        /// <summary>
        /// Update an existing course Update an existing course by Id
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Update an existent course</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Course</returns>
        public async System.Threading.Tasks.Task<Course> UpdateCourseAsync (Course course, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<Course> localVarResponse = await UpdateCourseWithHttpInfoAsync(course, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update an existing course Update an existing course by Id
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="course">Update an existent course</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Course)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Course>> UpdateCourseWithHttpInfoAsync (Course course, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'course' is set
            if (course == null)
                throw new ApiException(400, "Missing required parameter 'course' when calling CourseApi->UpdateCourse");

            var localVarPath = "/course";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (course != null && course.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(course); // http body (model) parameter
            }
            else
            {
                localVarPostBody = course; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateCourse", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Course>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Course) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Course)));
        }

    }
}
