/*
 * Swagger Student Management System - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading;
using RestSharp;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStudentApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Add a new student
        /// </summary>
        /// <remarks>
        /// Add a new student
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Create a new student</param>
        /// <returns>Student</returns>
        Student AddStudent (Student student);

        /// <summary>
        /// Add a new student
        /// </summary>
        /// <remarks>
        /// Add a new student
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Create a new student</param>
        /// <returns>ApiResponse of Student</returns>
        ApiResponse<Student> AddStudentWithHttpInfo (Student student);
        /// <summary>
        /// Deletes a student
        /// </summary>
        /// <remarks>
        /// delete a student
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">Student id to delete</param>
        /// <returns>Student</returns>
        Student DeleteStudent (long studentId);

        /// <summary>
        /// Deletes a student
        /// </summary>
        /// <remarks>
        /// delete a student
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">Student id to delete</param>
        /// <returns>ApiResponse of Student</returns>
        ApiResponse<Student> DeleteStudentWithHttpInfo (long studentId);
        /// <summary>
        /// Find student by ID
        /// </summary>
        /// <remarks>
        /// Returns a single student
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">ID of student to return</param>
        /// <returns>Student</returns>
        Student GetStudent (long studentId);

        /// <summary>
        /// Find student by ID
        /// </summary>
        /// <remarks>
        /// Returns a single student
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">ID of student to return</param>
        /// <returns>ApiResponse of Student</returns>
        ApiResponse<Student> GetStudentWithHttpInfo (long studentId);
        /// <summary>
        /// Get list of all students
        /// </summary>
        /// <remarks>
        /// Returns list of students
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List<Student></returns>
        List<Student> GetStudentList ();

        /// <summary>
        /// Get list of all students
        /// </summary>
        /// <remarks>
        /// Returns list of students
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List<Student></returns>
        ApiResponse<List<Student>> GetStudentListWithHttpInfo ();
        /// <summary>
        /// Update an existing student
        /// </summary>
        /// <remarks>
        /// Update an existing student by Id
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Update an existent student</param>
        /// <returns>Student</returns>
        Student UpdateStudent (Student student);

        /// <summary>
        /// Update an existing student
        /// </summary>
        /// <remarks>
        /// Update an existing student by Id
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Update an existent student</param>
        /// <returns>ApiResponse of Student</returns>
        ApiResponse<Student> UpdateStudentWithHttpInfo (Student student);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Add a new student
        /// </summary>
        /// <remarks>
        /// Add a new student
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Create a new student</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Student</returns>
        System.Threading.Tasks.Task<Student> AddStudentAsync (Student student, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Add a new student
        /// </summary>
        /// <remarks>
        /// Add a new student
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Create a new student</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Student)</returns>
        System.Threading.Tasks.Task<ApiResponse<Student>> AddStudentWithHttpInfoAsync (Student student, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Deletes a student
        /// </summary>
        /// <remarks>
        /// delete a student
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">Student id to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Student</returns>
        System.Threading.Tasks.Task<Student> DeleteStudentAsync (long studentId, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Deletes a student
        /// </summary>
        /// <remarks>
        /// delete a student
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">Student id to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Student)</returns>
        System.Threading.Tasks.Task<ApiResponse<Student>> DeleteStudentWithHttpInfoAsync (long studentId, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Find student by ID
        /// </summary>
        /// <remarks>
        /// Returns a single student
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">ID of student to return</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Student</returns>
        System.Threading.Tasks.Task<Student> GetStudentAsync (long studentId, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Find student by ID
        /// </summary>
        /// <remarks>
        /// Returns a single student
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">ID of student to return</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Student)</returns>
        System.Threading.Tasks.Task<ApiResponse<Student>> GetStudentWithHttpInfoAsync (long studentId, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Get list of all students
        /// </summary>
        /// <remarks>
        /// Returns list of students
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of List<Student></returns>
        System.Threading.Tasks.Task<List<Student>> GetStudentListAsync (CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Get list of all students
        /// </summary>
        /// <remarks>
        /// Returns list of students
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (List&lt;Student&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Student>>> GetStudentListWithHttpInfoAsync (CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Update an existing student
        /// </summary>
        /// <remarks>
        /// Update an existing student by Id
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Update an existent student</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Student</returns>
        System.Threading.Tasks.Task<Student> UpdateStudentAsync (Student student, CancellationToken cancellationToken = default(CancellationToken));

        /// <summary>
        /// Update an existing student
        /// </summary>
        /// <remarks>
        /// Update an existing student by Id
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Update an existent student</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Student)</returns>
        System.Threading.Tasks.Task<ApiResponse<Student>> UpdateStudentWithHttpInfoAsync (Student student, CancellationToken cancellationToken = default(CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class StudentApi : IStudentApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StudentApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StudentApi(String basePath)
        {
            this.Configuration = new Org.OpenAPITools.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StudentApi"/> class
        /// </summary>
        /// <returns></returns>
        public StudentApi()
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.Default;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StudentApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StudentApi(Org.OpenAPITools.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Org.OpenAPITools.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Add a new student Add a new student
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Create a new student</param>
        /// <returns>Student</returns>
        public Student AddStudent (Student student)
        {
             ApiResponse<Student> localVarResponse = AddStudentWithHttpInfo(student);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Add a new student Add a new student
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Create a new student</param>
        /// <returns>ApiResponse of Student</returns>
        public ApiResponse<Student> AddStudentWithHttpInfo (Student student)
        {
            // verify the required parameter 'student' is set
            if (student == null)
                throw new ApiException(400, "Missing required parameter 'student' when calling StudentApi->AddStudent");

            var localVarPath = "/student";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (student != null && student.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(student); // http body (model) parameter
            }
            else
            {
                localVarPostBody = student; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddStudent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Student>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Student) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Student)));
        }

        /// <summary>
        /// Add a new student Add a new student
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Create a new student</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Student</returns>
        public async System.Threading.Tasks.Task<Student> AddStudentAsync (Student student, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<Student> localVarResponse = await AddStudentWithHttpInfoAsync(student, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Add a new student Add a new student
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Create a new student</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Student)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Student>> AddStudentWithHttpInfoAsync (Student student, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'student' is set
            if (student == null)
                throw new ApiException(400, "Missing required parameter 'student' when calling StudentApi->AddStudent");

            var localVarPath = "/student";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (student != null && student.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(student); // http body (model) parameter
            }
            else
            {
                localVarPostBody = student; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddStudent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Student>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Student) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Student)));
        }

        /// <summary>
        /// Deletes a student delete a student
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">Student id to delete</param>
        /// <returns>Student</returns>
        public Student DeleteStudent (long studentId)
        {
             ApiResponse<Student> localVarResponse = DeleteStudentWithHttpInfo(studentId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Deletes a student delete a student
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">Student id to delete</param>
        /// <returns>ApiResponse of Student</returns>
        public ApiResponse<Student> DeleteStudentWithHttpInfo (long studentId)
        {
            // verify the required parameter 'studentId' is set
            if (studentId == null)
                throw new ApiException(400, "Missing required parameter 'studentId' when calling StudentApi->DeleteStudent");

            var localVarPath = "/student/{studentId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (studentId != null) localVarPathParams.Add("studentId", this.Configuration.ApiClient.ParameterToString(studentId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteStudent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Student>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Student) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Student)));
        }

        /// <summary>
        /// Deletes a student delete a student
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">Student id to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Student</returns>
        public async System.Threading.Tasks.Task<Student> DeleteStudentAsync (long studentId, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<Student> localVarResponse = await DeleteStudentWithHttpInfoAsync(studentId, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Deletes a student delete a student
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">Student id to delete</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Student)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Student>> DeleteStudentWithHttpInfoAsync (long studentId, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'studentId' is set
            if (studentId == null)
                throw new ApiException(400, "Missing required parameter 'studentId' when calling StudentApi->DeleteStudent");

            var localVarPath = "/student/{studentId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (studentId != null) localVarPathParams.Add("studentId", this.Configuration.ApiClient.ParameterToString(studentId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DeleteStudent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Student>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Student) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Student)));
        }

        /// <summary>
        /// Find student by ID Returns a single student
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">ID of student to return</param>
        /// <returns>Student</returns>
        public Student GetStudent (long studentId)
        {
             ApiResponse<Student> localVarResponse = GetStudentWithHttpInfo(studentId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Find student by ID Returns a single student
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">ID of student to return</param>
        /// <returns>ApiResponse of Student</returns>
        public ApiResponse<Student> GetStudentWithHttpInfo (long studentId)
        {
            // verify the required parameter 'studentId' is set
            if (studentId == null)
                throw new ApiException(400, "Missing required parameter 'studentId' when calling StudentApi->GetStudent");

            var localVarPath = "/student/{studentId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (studentId != null) localVarPathParams.Add("studentId", this.Configuration.ApiClient.ParameterToString(studentId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStudent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Student>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Student) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Student)));
        }

        /// <summary>
        /// Find student by ID Returns a single student
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">ID of student to return</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Student</returns>
        public async System.Threading.Tasks.Task<Student> GetStudentAsync (long studentId, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<Student> localVarResponse = await GetStudentWithHttpInfoAsync(studentId, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Find student by ID Returns a single student
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="studentId">ID of student to return</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Student)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Student>> GetStudentWithHttpInfoAsync (long studentId, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'studentId' is set
            if (studentId == null)
                throw new ApiException(400, "Missing required parameter 'studentId' when calling StudentApi->GetStudent");

            var localVarPath = "/student/{studentId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (studentId != null) localVarPathParams.Add("studentId", this.Configuration.ApiClient.ParameterToString(studentId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStudent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Student>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Student) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Student)));
        }

        /// <summary>
        /// Get list of all students Returns list of students
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List<Student></returns>
        public List<Student> GetStudentList ()
        {
             ApiResponse<List<Student>> localVarResponse = GetStudentListWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get list of all students Returns list of students
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List<Student></returns>
        public ApiResponse<List<Student>> GetStudentListWithHttpInfo ()
        {

            var localVarPath = "/student";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStudentList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Student>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Student>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Student>)));
        }

        /// <summary>
        /// Get list of all students Returns list of students
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of List<Student></returns>
        public async System.Threading.Tasks.Task<List<Student>> GetStudentListAsync (CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<List<Student>> localVarResponse = await GetStudentListWithHttpInfoAsync(cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get list of all students Returns list of students
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (List&lt;Student&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Student>>> GetStudentListWithHttpInfoAsync (CancellationToken cancellationToken = default(CancellationToken))
        {

            var localVarPath = "/student";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetStudentList", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Student>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (List<Student>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Student>)));
        }

        /// <summary>
        /// Update an existing student Update an existing student by Id
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Update an existent student</param>
        /// <returns>Student</returns>
        public Student UpdateStudent (Student student)
        {
             ApiResponse<Student> localVarResponse = UpdateStudentWithHttpInfo(student);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update an existing student Update an existing student by Id
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Update an existent student</param>
        /// <returns>ApiResponse of Student</returns>
        public ApiResponse<Student> UpdateStudentWithHttpInfo (Student student)
        {
            // verify the required parameter 'student' is set
            if (student == null)
                throw new ApiException(400, "Missing required parameter 'student' when calling StudentApi->UpdateStudent");

            var localVarPath = "/student";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (student != null && student.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(student); // http body (model) parameter
            }
            else
            {
                localVarPostBody = student; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateStudent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Student>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Student) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Student)));
        }

        /// <summary>
        /// Update an existing student Update an existing student by Id
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Update an existent student</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of Student</returns>
        public async System.Threading.Tasks.Task<Student> UpdateStudentAsync (Student student, CancellationToken cancellationToken = default(CancellationToken))
        {
             ApiResponse<Student> localVarResponse = await UpdateStudentWithHttpInfoAsync(student, cancellationToken);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update an existing student Update an existing student by Id
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="student">Update an existent student</param>
        /// <param name="cancellationToken">Cancellation Token to cancel request (optional) </param>
        /// <returns>Task of ApiResponse (Student)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Student>> UpdateStudentWithHttpInfoAsync (Student student, CancellationToken cancellationToken = default(CancellationToken))
        {
            // verify the required parameter 'student' is set
            if (student == null)
                throw new ApiException(400, "Missing required parameter 'student' when calling StudentApi->UpdateStudent");

            var localVarPath = "/student";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (student != null && student.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(student); // http body (model) parameter
            }
            else
            {
                localVarPostBody = student; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType, cancellationToken);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateStudent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Student>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (Student) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Student)));
        }

    }
}
