/*
Code Generation API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GenerateCodePost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateCodePost200Response{}

// GenerateCodePost200Response struct for GenerateCodePost200Response
type GenerateCodePost200Response struct {
	// A message indicating that code generation was successful
	Message *string `json:"message,omitempty"`
}

// NewGenerateCodePost200Response instantiates a new GenerateCodePost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateCodePost200Response() *GenerateCodePost200Response {
	this := GenerateCodePost200Response{}
	return &this
}

// NewGenerateCodePost200ResponseWithDefaults instantiates a new GenerateCodePost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateCodePost200ResponseWithDefaults() *GenerateCodePost200Response {
	this := GenerateCodePost200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GenerateCodePost200Response) GetMessage() string {
	if o == nil || isNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateCodePost200Response) GetMessageOk() (*string, bool) {
	if o == nil || isNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GenerateCodePost200Response) HasMessage() bool {
	if o != nil && !isNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GenerateCodePost200Response) SetMessage(v string) {
	o.Message = &v
}

func (o GenerateCodePost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateCodePost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGenerateCodePost200Response struct {
	value *GenerateCodePost200Response
	isSet bool
}

func (v NullableGenerateCodePost200Response) Get() *GenerateCodePost200Response {
	return v.value
}

func (v *NullableGenerateCodePost200Response) Set(val *GenerateCodePost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateCodePost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateCodePost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateCodePost200Response(val *GenerateCodePost200Response) *NullableGenerateCodePost200Response {
	return &NullableGenerateCodePost200Response{value: val, isSet: true}
}

func (v NullableGenerateCodePost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateCodePost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


