/*
Code Generation API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GenerateCodePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateCodePostRequest{}

// GenerateCodePostRequest struct for GenerateCodePostRequest
type GenerateCodePostRequest struct {
	// The programming language to generate code for
	Language string `json:"language"`
	// The URL of the OpenAPI specification to generate code from
	OpenAPIUrl string `json:"openAPIUrl"`
}

// NewGenerateCodePostRequest instantiates a new GenerateCodePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateCodePostRequest(language string, openAPIUrl string) *GenerateCodePostRequest {
	this := GenerateCodePostRequest{}
	this.Language = language
	this.OpenAPIUrl = openAPIUrl
	return &this
}

// NewGenerateCodePostRequestWithDefaults instantiates a new GenerateCodePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateCodePostRequestWithDefaults() *GenerateCodePostRequest {
	this := GenerateCodePostRequest{}
	return &this
}

// GetLanguage returns the Language field value
func (o *GenerateCodePostRequest) GetLanguage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Language
}

// GetLanguageOk returns a tuple with the Language field value
// and a boolean to check if the value has been set.
func (o *GenerateCodePostRequest) GetLanguageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Language, true
}

// SetLanguage sets field value
func (o *GenerateCodePostRequest) SetLanguage(v string) {
	o.Language = v
}

// GetOpenAPIUrl returns the OpenAPIUrl field value
func (o *GenerateCodePostRequest) GetOpenAPIUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OpenAPIUrl
}

// GetOpenAPIUrlOk returns a tuple with the OpenAPIUrl field value
// and a boolean to check if the value has been set.
func (o *GenerateCodePostRequest) GetOpenAPIUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OpenAPIUrl, true
}

// SetOpenAPIUrl sets field value
func (o *GenerateCodePostRequest) SetOpenAPIUrl(v string) {
	o.OpenAPIUrl = v
}

func (o GenerateCodePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateCodePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["language"] = o.Language
	toSerialize["openAPIUrl"] = o.OpenAPIUrl
	return toSerialize, nil
}

type NullableGenerateCodePostRequest struct {
	value *GenerateCodePostRequest
	isSet bool
}

func (v NullableGenerateCodePostRequest) Get() *GenerateCodePostRequest {
	return v.value
}

func (v *NullableGenerateCodePostRequest) Set(val *GenerateCodePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateCodePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateCodePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateCodePostRequest(val *GenerateCodePostRequest) *NullableGenerateCodePostRequest {
	return &NullableGenerateCodePostRequest{value: val, isSet: true}
}

func (v NullableGenerateCodePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateCodePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


