/*
 * Swagger Petstore - OpenAPI 3.0
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
 *
 * API version: 1.0.11
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "///go"
)

func main() {
	log.Printf("Server started")

	CategoryApiService := openapi.NewCategoryApiService()
	CategoryApiController := openapi.NewCategoryApiController(CategoryApiService)

	OrderApiService := openapi.NewOrderApiService()
	OrderApiController := openapi.NewOrderApiController(OrderApiService)

	PetApiService := openapi.NewPetApiService()
	PetApiController := openapi.NewPetApiController(PetApiService)

	ProductApiService := openapi.NewProductApiService()
	ProductApiController := openapi.NewProductApiController(ProductApiService)

	UserApiService := openapi.NewUserApiService()
	UserApiController := openapi.NewUserApiController(UserApiService)

	router := openapi.NewRouter(CategoryApiController, OrderApiController, PetApiController, ProductApiController, UserApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
