/*
 * Swagger Student Management System - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.11
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "///go"
)

func main() {
	log.Printf("Server started")

	CourseApiService := openapi.NewCourseApiService()
	CourseApiController := openapi.NewCourseApiController(CourseApiService)

	StudentApiService := openapi.NewStudentApiService()
	StudentApiController := openapi.NewStudentApiController(StudentApiService)

	router := openapi.NewRouter(CourseApiController, StudentApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
