=begin
Code Generation API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "_generate_code_post_200_response".pluralize.to_sym, id: false do |t|
      t.string :message

      t.timestamps
    end

    create_table "_generate_code_post_400_response".pluralize.to_sym, id: false do |t|
      t.string :message

      t.timestamps
    end

    create_table "_generate_code_post_request".pluralize.to_sym, id: false do |t|
      t.string :language
      t.string :open_api_url

      t.timestamps
    end

  end
end
