=begin
Swagger Student Management System - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.11
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "course".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :name
      t.string :desc

      t.timestamps
    end

    create_table "student".pluralize.to_sym, id: false do |t|
      t.integer :id
      t.string :name
      t.string :address
      t.string :email
      t.string :phone

      t.timestamps
    end

  end
end
