/**
 * Swagger Student Management System - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerStudentManagementSystemOpenApi30);
  }
}(this, function(expect, SwaggerStudentManagementSystemOpenApi30) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerStudentManagementSystemOpenApi30.CourseApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CourseApi', function() {
    describe('addCourse', function() {
      it('should call addCourse successfully', function(done) {
        //uncomment below and update the code to test addCourse
        //instance.addCourse(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCourse', function() {
      it('should call deleteCourse successfully', function(done) {
        //uncomment below and update the code to test deleteCourse
        //instance.deleteCourse(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCourse', function() {
      it('should call getCourse successfully', function(done) {
        //uncomment below and update the code to test getCourse
        //instance.getCourse(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCourseList', function() {
      it('should call getCourseList successfully', function(done) {
        //uncomment below and update the code to test getCourseList
        //instance.getCourseList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCourse', function() {
      it('should call updateCourse successfully', function(done) {
        //uncomment below and update the code to test updateCourse
        //instance.updateCourse(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
