/*
 * Swagger Student Management System - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.11
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// CourseApiService is a service that implements the logic for the CourseApiServicer
// This service should implement the business logic for every endpoint for the CourseApi API.
// Include any external packages or services that will be required by this service.
type CourseApiService struct {
}

// NewCourseApiService creates a default api service
func NewCourseApiService() CourseApiServicer {
	return &CourseApiService{}
}

// AddCourse - Add a new course
func (s *CourseApiService) AddCourse(ctx context.Context, course Course) (ImplResponse, error) {
	// TODO - update AddCourse with the required logic for this service method.
	// Add api_course_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Course{}) or use other options such as http.Ok ...
	//return Response(200, Course{}), nil

	//TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	//return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddCourse method not implemented")
}

// DeleteCourse - Deletes a course
func (s *CourseApiService) DeleteCourse(ctx context.Context, courseId int64) (ImplResponse, error) {
	// TODO - update DeleteCourse with the required logic for this service method.
	// Add api_course_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Course{}) or use other options such as http.Ok ...
	//return Response(200, Course{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteCourse method not implemented")
}

// GetCourse - Find course by ID
func (s *CourseApiService) GetCourse(ctx context.Context, courseId int64) (ImplResponse, error) {
	// TODO - update GetCourse with the required logic for this service method.
	// Add api_course_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Course{}) or use other options such as http.Ok ...
	//return Response(200, Course{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetCourse method not implemented")
}

// GetCourseList - Get list of all courses
func (s *CourseApiService) GetCourseList(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetCourseList with the required logic for this service method.
	// Add api_course_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Course{}) or use other options such as http.Ok ...
	//return Response(200, []Course{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetCourseList method not implemented")
}

// UpdateCourse - Update an existing course
func (s *CourseApiService) UpdateCourse(ctx context.Context, course Course) (ImplResponse, error) {
	// TODO - update UpdateCourse with the required logic for this service method.
	// Add api_course_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Course{}) or use other options such as http.Ok ...
	//return Response(200, Course{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	//TODO: Uncomment the next line to return response Response(405, {}) or use other options such as http.Ok ...
	//return Response(405, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateCourse method not implemented")
}
