/*
 * Swagger Student Management System - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.11
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Course struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Desc string `json:"desc,omitempty"`
}

// AssertCourseRequired checks if the required fields are not zero-ed
func AssertCourseRequired(obj Course) error {
	return nil
}

// AssertRecurseCourseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Course (e.g. [][]Course), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCourseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCourse, ok := obj.(Course)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCourseRequired(aCourse)
	})
}
