/*
 * Code Generation API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GenerateCodePostRequest struct {

	// The programming language to generate code for
	Language string `json:"language"`

	// The URL of the OpenAPI specification to generate code from
	OpenAPIUrl string `json:"openAPIUrl"`
}

// AssertGenerateCodePostRequestRequired checks if the required fields are not zero-ed
func AssertGenerateCodePostRequestRequired(obj GenerateCodePostRequest) error {
	elements := map[string]interface{}{
		"language": obj.Language,
		"openAPIUrl": obj.OpenAPIUrl,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseGenerateCodePostRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GenerateCodePostRequest (e.g. [][]GenerateCodePostRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGenerateCodePostRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGenerateCodePostRequest, ok := obj.(GenerateCodePostRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGenerateCodePostRequestRequired(aGenerateCodePostRequest)
	})
}
