=begin
Code Generation API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class GenerateCodePostRequest < ApplicationRecord
  validates_presence_of :language
  validates_presence_of :open_api_url

end
