=begin
Swagger Student Management System - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.11
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class Student < ApplicationRecord

end
