/**
* Code Generation API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server.models


/**
 * 
 * @param message A message indicating that code generation was successful
 */
data class GenerateCodePost200Response(
    /* A message indicating that code generation was successful */
    val message: kotlin.String? = null
) 

