=begin
Swagger Student Management System - OpenAPI 3.0

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.11
Generated by: https://github.com/openapitools/openapi-generator.git

=end
Rails.application.routes.draw do

  def add_openapi_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_openapi_route 'POST', '/api/v3/course', controller_name: 'course', action_name: 'create'
  add_openapi_route 'DELETE', '/api/v3/course/{courseId}', controller_name: 'course', action_name: 'destroy'
  add_openapi_route 'GET', '/api/v3/course/{courseId}', controller_name: 'course', action_name: 'show'
  add_openapi_route 'GET', '/api/v3/course', controller_name: 'course', action_name: 'index'
  add_openapi_route 'PUT', '/api/v3/course', controller_name: 'course', action_name: 'update_course'
  add_openapi_route 'POST', '/api/v3/student', controller_name: 'student', action_name: 'create'
  add_openapi_route 'DELETE', '/api/v3/student/{studentId}', controller_name: 'student', action_name: 'destroy'
  add_openapi_route 'GET', '/api/v3/student/{studentId}', controller_name: 'student', action_name: 'show'
  add_openapi_route 'GET', '/api/v3/student', controller_name: 'student', action_name: 'index'
  add_openapi_route 'PUT', '/api/v3/student', controller_name: 'student', action_name: 'update_student'
end
